# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run linter, tests, and build script for React backend

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: "./server/package-lock.json"

    - name: Install and check node packages
      run: |
        cd server
        npm ci
    - name: Run linter
      run: |
        cd server
        npm run lint-fix
    - name: Check dependencies 
      run: |
        cd server
        npm install -g npm-check
        npm-check --skip-unused
    - name: Run tests
      run: | 
        cd server
        npm run deploy-test